name: Weekly Stock Data Update

on:
  schedule:
    - cron: '0 0 * * 6' # Runs every Saturday at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Update to latest version

      - name: Set up Python
        uses: actions/setup-python@v5 # Update to latest version
        with:
          python-version: '3.10' # Upgrade to Python 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance==0.2.44 google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client pandas
          pip check  # Verify dependency compatibility

      - name: Set up credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json

      - name: Run script
        run: python fetch_stock_data.py
